"""Constantes del notebook legado. Fuente única: no se duplican en otros módulos."""

from __future__ import annotations

COL_TIEMPO = "Fecha"

# Tres claves de este mapa no coinciden con ninguna cabecera real del xlsx
# ('NRO CORRESPONSALES TOTALES', 'Key', 'MONTO CREDITO CONSUMO HOMBRES' con doble espacio).
# Se conservan tal cual: el modo notebook debe reproducir el comportamiento, incluido el silencio.
RENAME_MAP = {
    "Depto Base": "departamento",
    "Año": "anio",
    "Key": "key",
    "Poblacion": "poblacion",
    "Capital": "capital",
    "NRO CORRESPONSALES PROPIOS": "nro_corresp_propios",
    "NRO CORRESPONSALES TERCERIZADOS": "nro_corresp_terceros",
    "NRO CORRESPONSALES ACTIVOS": "nro_corresp_activos",
    "NRO CORRESPONSALES TOTALES": "nro_corresp_totales",
    "NRO DEPOSITOS": "nro_depositos",
    "MONTO DEPOSITOS": "monto_depositos",
    "NRO GIROS ENVIADOS": "nro_giros_env",
    "MONTO GIROS ENVIADOS": "monto_giros_env",
    "NRO GIROS RECIBIDOS": "nro_giros_rec",
    "MONTO GIROS RECIBIDOS": "monto_giros_rec",
    "NRO PAGOS": "nro_pagos",
    "MONTO PAGOS": "monto_pagos",
    "NRO RETIROS": "nro_retiros",
    "MONTO RETIROS": "monto_retiros",
    "NRO TRANSFERENCIAS": "nro_transf",
    "MONTO TRANSFERENCIAS": "monto_transf",
    "NRO TOTAL": "nro_total",
    "MONTO TOTAL": "monto_total",
    "NRO CTA AHORRO HASTA 1 SMMLV": "nro_cta_ah_hasta1smmlv",
    "SALDO CTA AHORRO HASTA 1 SMMLV": "saldo_cta_ah_hasta1smmlv",
    "NRO CTA AHORRO > 1 SMMLV HASTA 3 SMMLV": "nro_cta_ah_1a3smmlv",
    "SALDO CTA AHORRO> 1 SMMLV HASTA 3 SMMLV": "saldo_cta_ah_1a3smmlv",
    "NRO CTA AHORRO> 3 SMMLV HASTA 5 SMMLV": "nro_cta_ah_3a5smmlv",
    "SALDO CTA AHORRO> 3 SMMLV HASTA 5 SMMLV": "saldo_cta_ah_3a5smmlv",
    "NRO CTA AHORRO ACTIVAS": "nro_cta_ah_activas",
    "SALDO CTA AHORRO ACTIVAS": "saldo_cta_ah_activas",
    "NRO CTA AHORRO MUJERES": "nro_cta_ah_mujeres",
    "NRO CTA AHORRO HOMBRES": "nro_cta_ah_hombres",
    "NRO TOTAL CTA AHORROS": "nro_total_cta_ah",
    "SALDO TOTAL CTA AHORROS": "saldo_total_cta_ah",
    "NRO CTA AHORRO ELECTRONICAS ACTIVAS": "nro_cta_elect_activas",
    "SALDO CTA AHORRO ELECTRONICAS ACTIVAS": "saldo_cta_elect_activas",
    "NRO CTA AHORRO ELECTRONICAS MUJERES": "nro_cta_elect_mujeres",
    "NRO CTA AHORRO ELECTRONICAS HOMBRES": "nro_cta_elect_hombres",
    "NRO TOTAL CTA AHORROS ELECTRONICAS": "nro_total_cta_elect",
    "SALDO TOTAL CTA AHORROS ELECTRONICAS": "saldo_total_cta_elect",
    "NRO CREDITO CONSUMO MUJERES": "nro_cred_cons_mujeres",
    "MONTO CREDITO CONSUMO MUJERES": "monto_cred_cons_mujeres",
    "NRO CREDITO CONSUMO HOMBRES": "nro_cred_cons_hombres",
    "MONTO CREDITO CONSUMO HOMBRES": "monto_cred_cons_hombres",
    "NRO TOTAL CREDITO CONSUMO": "nro_total_cred_cons",
    "MONTO TOTAL CREDITO CONSUMO": "monto_total_cred_cons",
    "NRO CREDITO VIVIENDA MUJERES": "nro_cred_viv_mujeres",
    "MONTO CREDITO VIVIENDA MUJERES": "monto_cred_viv_mujeres",
    "NRO CREDITO VIVIENDA HOMBRES": "nro_cred_viv_hombres",
    "MONTO CREDITO VIVIENDA HOMBRES": "monto_cred_viv_hombres",
    "NRO TOTAL CREDITO VIVIENDA": "nro_total_cred_viv",
    "MONTO TOTAL CREDITO VIVIENDA": "monto_total_cred_viv",
    "NRO MICROCREDITO HASTA 1 SMMLV": "nro_micro_hasta1smmlv",
    "MONTO MICROCREDITO HASTA 1 SMMLV": "monto_micro_hasta1smmlv",
    "NRO MICROCREDITO MUJERES": "nro_micro_mujeres",
    "MONTO MICROCREDITO MUJERES": "monto_micro_mujeres",
    "NRO MICROCREDITO HOMBRES": "nro_micro_hombres",
    "MONTO MICROCREDITO HOMBRES": "monto_micro_hombres",
    "NRO TOTAL MICROCREDITO": "nro_total_micro",
    "MONTO TOTAL MICROCREDITO": "monto_total_micro",
    "Total General Hogar Internet": "hogares_internet_total",
    "Conexión a internet %": "internet_pct",
    "Fijo %": "internet_fijo_pct",
    "Movil %": "internet_movil_pct",
    "Fijo Movil %": "internet_fijo_movil_pct",
    "Años promedio de educación": "educacion_anios",
    "IPC %": "IPC_pct",
    "Empleo Formal": "Empleo_Formal",
    "Empleo Informal": "Empleo_Informal",
    "Superficie Km2": "Superficie_km2",
    "Densidad Poblacional": "Densidad_Poblacional",
    "PIB Contribucion Al Total": "pib_contribucion_pct",
    "PIB Percapita": "pib_percapita",
    "PIB Crecimiento": "pib_crecimiento",
}

# Columnas crudas del xlsx que el notebook consume de verdad (21 de 102).
USED_RAW_COLUMNS = {
    "Año",
    "Fecha",
    "Depto Base",
    "NRO CORRESPONSALES ACTIVOS",
    "NRO DEPOSITOS",
    "NRO PAGOS",
    "NRO TRANSFERENCIAS",
    "NRO TOTAL",
    "NRO TOTAL CTA AHORROS",
    "MONTO TOTAL CREDITO CONSUMO",
    "MONTO TOTAL CREDITO VIVIENDA",
    "MONTO TOTAL MICROCREDITO",
    "Poblacion",
    "Conexión a internet %",
    "Años promedio de educación",
    "IPC %",
    "Empleo Formal",
    "Empleo Informal",
    "Densidad Poblacional",
    "PIB Percapita",
    "PIB Crecimiento",
}

VARS_PCA = [
    "d_acc_corresp",
    "d_acc_cta_ah",
    "d_acc_internet",
    "d_uso_pagos_pc",
    "d_uso_transf_pc",
    "d_uso_depositos_pc",
    "d_pro_micro",
    "d_pro_cred_cons",
    "d_pro_cred_viv",
]
VARS_PCA_SIN_INTERNET = [v for v in VARS_PCA if v != "d_acc_internet"]

LABELS_PCA = {
    "d_acc_corresp": "Corresponsales",
    "d_acc_cta_ah": "Cuentas ahorro",
    "d_acc_internet": "Internet (%)",
    "d_uso_pagos_pc": "Pagos digitales",
    "d_uso_transf_pc": "Transferencias",
    "d_uso_depositos_pc": "Depósitos",
    "d_pro_micro": "Microcrédito/PIB",
    "d_pro_cred_cons": "Créd. consumo/PIB",
    "d_pro_cred_viv": "Créd. vivienda/PIB",
}

DIMENSION_PCA = {
    "d_acc_corresp": "acceso",
    "d_acc_cta_ah": "acceso",
    "d_acc_internet": "acceso",
    "d_uso_pagos_pc": "uso",
    "d_uso_transf_pc": "uso",
    "d_uso_depositos_pc": "uso",
    "d_pro_micro": "profundidad",
    "d_pro_cred_cons": "profundidad",
    "d_pro_cred_viv": "profundidad",
}

CTRL = ["internet", "educacion", "densidad", "informalidad"]

REGION_LABEL = {0: "Andina", 1: "Caribe", 2: "Pacífica", 3: "Orinoquía", 4: "Amazonía"}

# Mapa de regiones del notebook, con sus variantes de escritura. La versión mantenida
# vive en dbt/seeds/xw_departamento_region.csv (por código DIVIPOLA); este se conserva
# solo para la reproducción exacta.
REGION_MAP = {
    "atlantico": 1,
    "atlántico": 1,
    "bolivar": 1,
    "bolívar": 1,
    "magdalena": 1,
    "la guajira": 1,
    "guajira": 1,
    "cesar": 1,
    "cordoba": 1,
    "córdoba": 1,
    "sucre": 1,
    "san andres": 1,
    "san andrés": 1,
    "san andres,prov y santa catalina": 1,
    "antioquia": 0,
    "boyaca": 0,
    "boyacá": 0,
    "caldas": 0,
    "cundinamarca": 0,
    "bogota": 0,
    "bogotá": 0,
    "bogota d.c.": 0,
    "bogotá d.c.": 0,
    "norte de santander": 0,
    "santander": 0,
    "risaralda": 0,
    "quindio": 0,
    "quindío": 0,
    "tolima": 0,
    "huila": 0,
    "choco": 2,
    "chocó": 2,
    "valle del cauca": 2,
    "valle": 2,
    "cauca": 2,
    "narino": 2,
    "nariño": 2,
    "arauca": 3,
    "casanare": 3,
    "meta": 3,
    "vichada": 3,
    "amazonas": 4,
    "caqueta": 4,
    "caquetá": 4,
    "guainia": 4,
    "guainía": 4,
    "guaviare": 4,
    "putumayo": 4,
    "vaupes": 4,
    "vaupés": 4,
}

VARS_LAG = [
    "crec_pib",
    "crec_pib_pc",
    "IIF",
    "log_IIF",
    "IIF_std",
    "IIF_PC1",
    "IIF_sin_net",
    "IIF_oos",
    "log_fintech_pc",
]

VARS_DESC = [
    "crec_pib",
    "crec_pib_pc",
    "log_fintech_pc",
    "d_acc_corresp",
    "d_acc_cta_ah",
    "d_acc_internet",
    "d_uso_pagos_pc",
    "d_uso_transf_pc",
    "d_uso_depositos_pc",
    "d_pro_micro",
    "d_pro_cred_cons",
    "d_pro_cred_viv",
    "educacion",
    "densidad",
    "informalidad",
    "IIF",
    "log_IIF",
]
