{
  "hash": "89a005467ae02fc829f4c73ca9ee7262",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Panel anual: inclusión financiera y crecimiento\"\nsubtitle: \"Treinta y tres departamentos, 2019 a 2025, con la batería contra la correlación espuria\"\n---\n\n\n\nLa pregunta es si el índice de inclusión financiera predice el crecimiento del PIB real per cápita de los\ndepartamentos. Todo lo de esta página sale de un solo archivo que escribe `uv run iif econ`\n(`data/processed/econ/resultados.json`); ninguna cifra viene de un cuaderno. El diseño está decidido en\nADR-016 y probado en `tests/test_econ.py` sobre paneles sintéticos, donde se sabe la verdad.\n\n::: {#90d9d890 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n\n**Muestra.** 33 departamentos, 2019 a 2025, N = 228.\nDependiente: tasa de crecimiento del PIB real per cápita. Regresor: índice compuesto estandarizado.\nControles: log_pib_rezago, tasa_urbanizacion. Efectos fijos de entidad y tiempo. Exposición inicial medida en\n2018, anterior a toda observación de la dependiente.\n\n:::\n:::\n\n\n## 1. Resultado principal\n\n::: {#6e7416c6 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n| Especificación                    |       β |     EE |     p | IC 95 %          |   N |   Dptos. | Errores        |\n|:----------------------------------|--------:|-------:|------:|:-----------------|----:|---------:|:---------------|\n| base: efectos de entidad y tiempo |  0.0007 | 0.006  | 0.902 | [-0.011, +0.013] | 228 |       33 | cluster        |\n| base con Driscoll-Kraay           |  0.0007 | 0.0037 | 0.84  | [-0.006, +0.008] | 228 |       33 | driscoll-kraay |\n| solo efectos de entidad           |  0.0242 | 0.005  | 0     | [+0.014, +0.034] | 228 |       33 | cluster        |\n| en cambios del índice             | -0.0071 | 0.0051 | 0.159 | [-0.017, +0.003] | 226 |       33 | cluster        |\n:::\n:::\n\n\nLa primera fila es la especificación base. La segunda repite el modelo con errores de Driscoll-Kraay, que\nadmiten dependencia entre departamentos dentro de un mismo año. La tercera **no es una alternativa**: es el\nmismo modelo sin efectos de tiempo, y se publica porque la distancia entre su coeficiente y el de la\nprimera fila es exactamente la parte de la relación que era tendencia nacional. La cuarta reemplaza el\nnivel del índice por su cambio anual.\n\n## 2. Por dimensión y con índices alternativos\n\n::: {#fae35968 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n| Especificación            |       β |     EE |     p | IC 95 %          |   N |   Dptos. |\n|:--------------------------|--------:|-------:|------:|:-----------------|----:|---------:|\n| dimensión: acceso         |  0.0013 | 0.0025 | 0.618 | [-0.004, +0.006] | 231 |       33 |\n| dimensión: uso            | -0.0037 | 0.0096 | 0.702 | [-0.023, +0.015] | 231 |       33 |\n| dimensión: profundidad    | -0.0208 | 0.0153 | 0.176 | [-0.051, +0.009] | 228 |       33 |\n| índice alternativo: PCA   |  0.0039 | 0.0063 | 0.536 | [-0.009, +0.016] | 228 |       33 |\n| índice alternativo: Sarma | -0.1049 | 0.1089 | 0.336 | [-0.320, +0.110] | 231 |       33 |\n:::\n:::\n\n\nAcceso, uso y profundidad entran cada una en su propia regresión: juntas medirían el efecto parcial de una\ndimensión manteniendo fijas las otras, que no es la pregunta cuando las tres se mueven a la vez por\nconstrucción. Los índices por PCA y por distancia de Sarma son las alternativas de ADR-015.\n\n## 3. Diagnósticos\n\n::: {#3cd2b1a4 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n\n| Prueba | Estadístico | Lectura |\n|---|---|---|\n| CD de Pesaran (residuos del modelo base) | 2.46 (p = 0.014; ρ̄ = 0.041) | dependencia transversal débil pero presente: por eso Driscoll-Kraay acompaña al clúster |\n| CIPS sobre el índice | -2.28 con T = 8 | T corto: la prueba se lee como indicio, no como veredicto |\n\nI de Moran del crecimiento por año, con inferencia por permutación sobre la contigüidad de los departamentos:\n\n|   Año |   I de Moran |     p |\n|------:|-------------:|------:|\n|  2019 |        0.008 | 0.953 |\n|  2020 |        0.156 | 0.139 |\n|  2021 |        0.034 | 0.754 |\n|  2022 |        0.222 | 0.039 |\n|  2023 |        0.018 | 0.881 |\n|  2024 |        0.09  | 0.439 |\n|  2025 |        0.225 | 0.047 |\n\n:::\n:::\n\n\nLa contigüidad no viene de una biblioteca espacial: dos departamentos son vecinos si comparten un arco en el\nTopoJSON del atlas, que guarda cada frontera una sola vez. Es exacto por construcción. El archipiélago no\ntoca a nadie y queda con fila de ceros, no con un vecino inventado.\n\n## 4. Diseños que no dependen de la exogeneidad del índice\n\n::: {#584ad3e0 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=6}\n| Especificación                           |      β |     EE |     p | IC 95 %          |   N |   Dptos. |\n|:-----------------------------------------|-------:|-------:|------:|:-----------------|----:|---------:|\n| CCE (cargas heterogéneas)                | 0.0014 | 0.0086 | 0.869 | [-0.016, +0.018] | 228 |       33 |\n| shift-share (exposición 2018 × adopción) | 0.0182 | 0.0067 | 0.007 | [+0.005, +0.031] | 223 |       32 |\n| SLX (rezago espacial del índice)         | 0.0046 | 0.0066 | 0.493 | [-0.009, +0.018] | 221 |       32 |\n:::\n:::\n\n\n- **CCE** añade las medias transversales de la dependiente y del regresor con una carga distinta por\n  departamento, sin efectos de tiempo: un choque nacional que golpea el doble a un departamento que a otro\n  deja de confundirse con el índice.\n- **Shift-share** sustituye el índice observado por la exposición de 2018 multiplicada por la adopción\n  nacional. Con efectos de tiempo identifica la pendiente diferencial de los departamentos que empezaron\n  más incluidos.\n- **SLX** añade la media del índice de los vecinos: si el coeficiente propio se sostiene, la relación no\n  era el reflejo de un vecindario.\n\n### El shift-share, contrastado contra sí mismo\n\n::: {#08539676 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=7}\n| Especificación                                       |      β |     EE |     p | IC 95 %          |   N |   Dptos. |\n|:-----------------------------------------------------|-------:|-------:|------:|:-----------------|----:|---------:|\n| placebo shift-share: ingreso inicial × adopcion      | 0.0088 | 0.0074 | 0.235 | [-0.006, +0.023] | 228 |       33 |\n| placebo shift-share: urbanizacion inicial × adopcion | 0.0506 | 0.0201 | 0.013 | [+0.011, +0.090] | 228 |       33 |\n:::\n:::\n\n\n::: {#7550269b .cell execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=8}\n\nCualquier condición inicial correlacionada con el índice produciría la misma pendiente diferencial si lo\nque hay es recuperación desigual y no inclusión. Con el ingreso inicial como exposición el coeficiente es\n+0.0088 (p = 0.235); con la urbanización inicial,\n+0.0506 (p = 0.013). En la carrera de caballos —índice e\ningreso iniciales en la misma ecuación— el índice queda en +0.0207 (p = 0.014) y el ingreso\nen -0.0050 (p = 0.567).\n\n:::\n:::\n\n\n## 5. Estudio de eventos alrededor de 2020\n\n::: {#32153bf1 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=9}\n|   Año |   k |   β (exposición 2018 × año) |     EE |\n|------:|----:|----------------------------:|-------:|\n|  2019 |  -1 |                      0      | 0      |\n|  2020 |   0 |                      0.0093 | 0.0104 |\n|  2021 |   1 |                     -0.0043 | 0.0122 |\n|  2022 |   2 |                      0.0139 | 0.0051 |\n|  2023 |   3 |                     -0.0022 | 0.0042 |\n|  2024 |   4 |                      0.0025 | 0.0026 |\n|  2025 |   5 |                      0.0072 | 0.0036 |\n:::\n:::\n\n\nLa exposición es el índice de 2018 estandarizado; el año de referencia es 2019. **Este diseño no puede\ncontrastar tendencias previas**: la dependiente empieza en 2019 y el choque es 2020, así que solo hay un\naño anterior y es el de referencia. Lo que mide es en qué años posteriores se separan los departamentos\nmás expuestos, y se publica con esa limitación escrita.\n\n## 6. Inferencia con pocos clústeres\n\n::: {#7c5fe40c .cell execution_count=10}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n\n| Procedimiento | Resultado |\n|---|---|\n| Bootstrap salvaje por clúster, nula impuesta, 999 réplicas de Rademacher sobre 33 departamentos | β = +0.0007, t = +0.15, **p = 0.886** |\n| Placebo: el índice barajado entre departamentos dentro de cada año, 499 permutaciones | β verdadero = +0.0007; placebos con media +0.0000 y DE 0.0018; **p = 0.682** |\n\n:::\n:::\n\n\nCon 33 clústeres el error estándar agrupado descansa en una asintótica que no se cumple; el bootstrap\nsalvaje con la nula impuesta es la corrección estándar para ese caso. El placebo baraja el índice dentro de\ncada año: conserva la trayectoria nacional y destruye solo la asignación territorial, que es la variación\nque identificaría un efecto.\n\n## 7. Lectura\n\n::: {#915be05f .cell execution_count=11}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=11}\n\nEl coeficiente del índice sobre el crecimiento es **+0.0007** con efectos fijos de entidad y\ntiempo (p = 0.90; bootstrap salvaje p = 0.89; placebo p = 0.68).\nSin efectos de tiempo sería +0.0242 (p < 0,001): esa diferencia es lo que valía la tendencia\nnacional. Las tres dimensiones, la especificación en cambios, el CCE, el SLX y los dos índices\nalternativos dan lo mismo. El único diseño con un coeficiente distinto de cero es el shift-share\n(+0.0182, p = 0.007). Sobrevive al ingreso inicial como exposición de placebo, pero la\nurbanización inicial produce una pendiente igual de significativa (+0.0506,\np = 0.013): lo que ese diseño recoge es que los departamentos más urbanos, que son\ntambién los más incluidos, crecieron más rápido en el periodo. Es una pendiente diferencial, no un efecto\ncausal del índice, y no se presenta como tal porque solo sobrevive a uno de los cuatro diseños y no\ndistingue inclusión de urbanización.\n\n:::\n:::\n\n\n",
    "supporting": [
      "panel_files"
    ],
    "filters": [],
    "includes": {}
  }
}