{
  "hash": "9f0ddcd78bb5563f6d4c276ea291be21",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Reproducción del notebook de la tesis\"\nsubtitle: \"Lo que da el código publicado, frente a lo que dice el documento\"\nexecute:\n  echo: false\n---\n\n\n\n::: {.callout-warning}\n## Tres objetos distintos\nEl **documento** defendido, el **notebook consolidado** que lo acompaña y el **análisis corregido** de este proyecto no dicen lo mismo. Esta página compara los dos primeros. El tercero está en construcción en [Metodología](metodologia/panel.qmd).\n:::\n\n## Entorno\n\n::: {#6ad7bfa0 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n- **python**: `3.11.15`\n- **pandas**: `3.0.5`\n- **numpy**: `2.4.6`\n- **linearmodels**: `7.0`\n- **sklearn**: `1.9.0`\n- **archivo**: `panel_fintech_colombia_trimestral.parquet`\n- **sha256**: `6c2cc3fdf757172e7b2bfb93de75b1a722fc88d81501129d712edbb5a4881d32`\n- **modo**: `notebook`\n:::\n:::\n\n\n## D1: la dependiente es anual repetida en trimestres\n\n::: {#7120b313 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n\n| Variable | mín. distintos por (depto, año) | máx. |\n|---|---|---|\n| `pib_percapita` | 1 | 1 |\n| `pib_crecimiento` | 1 | 1 |\n| `IPC_pct` | 1 | 1 |\n| `internet_pct` | 1 | 1 |\n| `educacion_anios` | 1 | 1 |\n| `Empleo_Informal` | 1 | 1 |\n\n- `pib_percapita` toma **5** valores distintos por departamento en 14 trimestres (uno por año).\n- El crecimiento es idéntico al del trimestre anterior en el **64.3%** de las observaciones.\n- `crec_pib_pc` es exactamente cero en el **64.3%**.\n\nConsecuencia: el panel tiene 462 filas pero 165 departamento-años de información sobre el crecimiento.\n\n:::\n:::\n\n\n## El índice\n\n::: {#8f97552a .cell execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n\n- KMO = **0.7189**, Bartlett χ² = 2543.45 (p = 0.0000).\n- Regla de retención del notebook: varianza acumulada ≥ 80 % → **4 componentes** (84.42 %). Kaiser (λ > 1) retendría 3.\n- Pesos de los componentes: [0.5539, 0.2058, 0.1625, 0.0778]. Correlación con cuentas de ahorro: 0.8684 (forzada por construcción).\n- Sin internet: corr(IIF, IIF sin internet) = 0.9933. Con pesos de 2017–2019: corr = 0.9947.\n\n:::\n:::\n\n\n### Cargas factoriales\n\n::: {#564e1d6c .cell execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n|                    |   PC1 (46.8%) |   PC2 (17.4%) |   PC3 (13.7%) |   PC4 (6.6%) |\n|:-------------------|--------------:|--------------:|--------------:|-------------:|\n| Corresponsales     |        0.4278 |       -0.0992 |        0.1468 |      -0.1472 |\n| Cuentas ahorro     |        0.3913 |        0.2576 |        0.1052 |       0.1934 |\n| Internet (%)       |        0.3532 |       -0.0277 |        0.1355 |      -0.6643 |\n| Pagos digitales    |        0.4165 |       -0.0934 |        0.1446 |      -0.1993 |\n| Transferencias     |        0.219  |       -0.6005 |       -0.1903 |       0.3483 |\n| Depósitos          |        0.3567 |       -0.4085 |       -0.0832 |       0.2796 |\n| Microcrédito/PIB   |       -0.0614 |       -0.1696 |       -0.7883 |      -0.4369 |\n| Créd. consumo/PIB  |        0.2717 |        0.4227 |       -0.4838 |       0.2395 |\n| Créd. vivienda/PIB |        0.336  |        0.4234 |       -0.1718 |       0.1101 |\n:::\n:::\n\n\n### Pesos implícitos por variable\n\nLo que el notebook nunca imprimió: el índice pondera el microcrédito con signo negativo.\n\n::: {#08ab2ca3 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=6}\n|                    |   peso implícito |\n|:-------------------|-----------------:|\n| Corresponsales     |           0.2289 |\n| Cuentas ahorro     |           0.3019 |\n| Internet (%)       |           0.1603 |\n| Pagos digitales    |           0.2195 |\n| Transferencias     |          -0.0061 |\n| Depósitos          |           0.1217 |\n| Microcrédito/PIB   |          -0.231  |\n| Créd. consumo/PIB  |           0.1775 |\n| Créd. vivienda/PIB |           0.2539 |\n:::\n:::\n\n\n## Tabla 6\n\n::: {#675240d8 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=7}\n```text\n  A1 FE-Est   | IIF                                β= +20.8640*** SE= 5.9913 p=0.0006 N= 429 R²=0.0239\n  A2 FE-Dyn   | IIF_lag1                           β= +57.8769*** SE= 7.6273 p=0.0000 N= 396 R²=0.1160\n  A3 2way FE  | IIF_lag1  ← REFERENCIA             β=  +0.3579    SE= 6.2724 p=0.9545 N= 396 R²=0.0058\n  A4 2way FE  | IIF       ← FALTABA                β=  -8.4388    SE= 6.9623 p=0.2262 N= 429 R²=0.0075\n  B1 FE-Est   | IIF                                β=  +3.0349    SE= 4.8141 p=0.5288 N= 462 R²=0.0708\n  B2 FE-Dyn   | IIF_lag1                           β= +35.5537*** SE= 5.9553 p=0.0000 N= 429 R²=0.1992\n  B3 FE-Dyn   | IIF_PC1_lag1                       β= +25.8399*** SE= 4.9779 p=0.0000 N= 429 R²=0.1955\n  B4 2way FE  | IIF_lag1                           β=  -5.7504    SE= 4.2043 p=0.1722 N= 429 R²=0.1907\n```\n:::\n:::\n\n\n::: {#6ad58c12 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=8}\n\nSobre la **misma muestra**, añadir efectos de tiempo mueve el coeficiente del IIF de **+57.88** (p = 0.0000, N = 396) a **+0.36** (p = 0.9545, N = 396) en el bloque per cápita, y de +35.55 a -5.75 en el agregado. El efecto que queda después de quitar el ciclo nacional es cero.\n\n:::\n:::\n\n\n## Diagnósticos\n\n::: {#1fe91e67 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=9}\n- Hausman como lo calcula el notebook: χ²(6) = 292.77. **No es un test válido**: ambos modelos usan covarianza clusterizada, así que la diferencia de covarianzas no es definida positiva. Se conserva solo para la comparación con el documento (33,93).\n- Mundlak: β_within = +17.264 (p = 0.0000), β_mean = +6.796 (p = 0.0615).\n- Correlación between = +0.1201, within = -0.1532.\n- Pesaran CD = **69.12** (p = 0.0000): dependencia transversal extrema; la dependiente es un ciclo nacional repetido 33 veces.\n- Error estándar de B2: clusterizado 5.955 → Driscoll-Kraay 37.022. El resultado principal deja de ser significativo.\n- Nickell (PIB agregado): ρ̂ = +0.4279, sesgo ≈ -0.1098 (26 % de ρ̂). Fórmula de AR(1) puro aplicada a un modelo con regresores: orientativa.\n- Nickell (PIB per cápita): ρ̂ = +0.1314, sesgo ≈ -0.0870 (66 % de ρ̂). Fórmula de AR(1) puro aplicada a un modelo con regresores: orientativa.\n:::\n:::\n\n\n## Robustez y heterogeneidad\n\n::: {#87ec5d8a .cell execution_count=10}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n```text\n  Pre-COVID | FE Entity                            β=  -1.0580    SE= 2.0690 p=0.6096 N= 264 R²=0.4733\n  Pre-COVID | two-way                              β=  -7.9795    SE= 5.7312 p=0.1652 N= 264 R²=0.4558\n  FE Entity | DK SE                                β= +35.5537    SE=37.0221 p=0.3375 N= 429 R²=0.1992\n  Trimming 1%                                      β= +30.2266*** SE= 6.0886 p=0.0000 N= 420 R²=0.3048\n  Winsorización 5%                                 β= +28.6497*** SE= 5.2424 p=0.0000 N= 429 R²=0.2461\n  IIF_lag2      | PIB pc                           β= +25.7220**  SE=10.1110 p=0.0114 N= 396 R²=0.0260\n  IIF_lag2 2way | PIB pc                           β=  +2.0966    SE= 5.5865 p=0.7077 N= 396 R²=0.0060\n  IIF sin internet | PIB pc  (D2)                  β= +57.7779*** SE= 7.1292 p=0.0000 N= 396 R²=0.1262\n  IIF sin internet 2way | PIB pc  (D2)             β=  +4.6279    SE= 4.1289 p=0.2631 N= 396 R²=0.0068\n  IIF out-of-sample | PIB pc (D3)                  β= +63.4259*** SE= 7.7934 p=0.0000 N= 396 R²=0.1396\n  IIF out-of-sample 2way | PIB pc (D3)             β=  +1.6526    SE= 5.6106 p=0.7685 N= 396 R²=0.0059\n  FE Entity + tendencia t_idx                      β= +45.4128*** SE= 5.6740 p=0.0000 N= 429 R²=0.2066\n  log(IIF)_lag1 | PIB pc                           β=  +8.1401*** SE= 1.9488 p=0.0000 N= 396 R²=0.0548\n```\n:::\n:::\n\n\n::: {#2ab97c09 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=11}\n| Region    |    beta |      se |      p |   N |   N_dep |\n|:----------|--------:|--------:|-------:|----:|--------:|\n| Andina    | 23.2643 |  9.1796 | 0.0125 | 143 |      11 |\n| Caribe    | 72.2255 | 23.563  | 0.0029 | 104 |       8 |\n| Pacífica  | 58.5644 |  8.3576 | 0      |  52 |       4 |\n| Orinoquía | 16.4008 | 12.7984 | 0.2071 |  52 |       4 |\n| Amazonía  | 50.9128 | 13.6983 | 0.0004 |  78 |       6 |\n\nPacífica y Orinoquía se estiman con 4 clústeres: un p = 0,0000 ahí es un artefacto de la inferencia clusterizada.\n:::\n:::\n\n\n## Verificación contra el documento\n\n::: {#f3fef04c .cell execution_count=12}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=12}\n| item                                   |   obtenido |   documento | estado          | nota                                        |\n|:---------------------------------------|-----------:|------------:|:----------------|:--------------------------------------------|\n| D1 pib_percapita distintos por depto   |     5      |             | DIAGNÓSTICO     | 5≈anual repetido / 14≈trimestral            |\n| D1 fracción crec_pib(t)==crec_pib(t-1) |     0.6429 |             | DIAGNÓSTICO     | 0.75 ⇒ dependiente sin variación trimestral |\n| D1 fracción crec_pib_pc == 0           |     0.6429 |             | DIAGNÓSTICO     | 0.75 ⇒ log-diff nulo dentro del año         |\n| KMO                                    |     0.7189 |      0.7189 | OK              |                                             |\n| Bartlett chi2                          |  2543.45   |   2543.45   | OK              |                                             |\n| Varianza acumulada 4 PC                |    84.4219 |     84.4    | OK              |                                             |\n| Corr orientación IIF~cuentas           |     0.8684 |      0.8684 | OK              |                                             |\n| Tabla6 A1 β                            |    20.864  |     31.1133 | DISCREPA        |                                             |\n| Tabla6 A1 SE                           |     5.9913 |      6.6263 | DISCREPA        |                                             |\n| Tabla6 A1 N                            |   429      |    396      | DISCREPA        |                                             |\n| Tabla6 A2 β                            |    57.8769 |     62.4924 | DISCREPA        |                                             |\n| Tabla6 A2 SE                           |     7.6273 |      8.3614 | DISCREPA        |                                             |\n| Tabla6 A2 N                            |   396      |    363      | DISCREPA        |                                             |\n| Tabla6 A3 β                            |     0.3579 |     -0.147  | DISCREPA        |                                             |\n| Tabla6 A3 SE                           |     6.2724 |      7.2027 | DISCREPA        |                                             |\n| Tabla6 A3 N                            |   396      |    363      | DISCREPA        |                                             |\n| Tabla6 A4 β                            |    -8.4388 |             | SIN DATO EN DOC |                                             |\n| Tabla6 A4 SE                           |     6.9623 |             | SIN DATO EN DOC |                                             |\n| Tabla6 A4 N                            |   429      |             | SIN DATO EN DOC |                                             |\n| Tabla6 B1 β                            |     3.0349 |      5.7043 | DISCREPA        |                                             |\n| Tabla6 B1 SE                           |     4.8141 |      5.5871 | DISCREPA        |                                             |\n| Tabla6 B1 N                            |   462      |    429      | DISCREPA        |                                             |\n| Tabla6 B2 β                            |    35.5537 |     35.5537 | OK              |                                             |\n| Tabla6 B2 SE                           |     5.9553 |      9.5553 | DISCREPA        |                                             |\n| Tabla6 B2 N                            |   429      |    429      | OK              |                                             |\n| Tabla6 B3 β                            |    25.8399 |     28.5079 | DISCREPA        |                                             |\n| Tabla6 B3 SE                           |     4.9779 |      4.8183 | DISCREPA        |                                             |\n| Tabla6 B3 N                            |   429      |    396      | DISCREPA        |                                             |\n| Tabla6 B4 β                            |    -5.7504 |     -4.9256 | DISCREPA        |                                             |\n| Tabla6 B4 SE                           |     4.2043 |      4.358  | DISCREPA        |                                             |\n| Tabla6 B4 N                            |   429      |    396      | DISCREPA        |                                             |\n| Hausman chi2                           |   292.774  |     33.93   | DISCREPA        |                                             |\n| Mundlak IIF_mean                       |     6.796  |      4.11   | DISCREPA        | doc=4.11 | inicial=1.85 | correcciones=6.77 |\n| Corr between                           |     0.1201 |      0.094  | DISCREPA        |                                             |\n| Corr within                            |    -0.1532 |     -0.164  | OK              |                                             |\n| rho Nickell (agregado)                 |     0.4279 |      0.4279 | OK              | el documento usa el ρ del modelo AGREGADO   |\n| Pre-COVID β                            |    -1.058  |      0.12   | DISCREPA        |                                             |\n| Pre-COVID R²                           |     0.4733 |      0.576  | DISCREPA        |                                             |\n| Pesaran CD                             |    69.1165 |     66.81   | OK              |                                             |\n| β semi-elasticidad log                 |     8.1401 |      5.344  | DISCREPA        |                                             |\n\n**Discrepancias: 25 de 40 filas.**\n:::\n:::\n\n\n### Por qué difieren\n\n- Todas las N de la Tabla 6 del documento son exactamente **33 menos** (una sección transversal) que las del notebook, salvo B2. El documento construyó los rezagos sobre una muestra ya recortada; el notebook los construye una vez sobre el panel completo. Cambiar la muestra cambia cada β.\n- El SE de B2 en la tabla del documento (9,5553) es una errata: el texto dice 5,96 y el notebook da 5,9553.\n- El Hausman difiere en un orden de magnitud porque, tal como está implementado, no es un estadístico estable.\n- Trece cifras guardadas en el notebook (`DOC_OTROS`) nunca se verifican: recorte, winsorización, Driscoll-Kraay, semi-elasticidad. Contadas a mano, las discrepancias reales rondan 32.\n\nConclusión operativa: el documento defendido no se reproduce desde el código publicado. Este proyecto no intenta rescatar aquellas cifras: rehace el análisis desde las fuentes primarias y publica la trazabilidad completa.\n\n",
    "supporting": [
      "reproduccion-tesis_files"
    ],
    "filters": [],
    "includes": {}
  }
}